// Ядро программы - ВСЕ функции в одном файле
const T=[],DC=['Артикул','Наименование','Ко-во, шт','Цена','Стоимость'];
let idC=0,actId=null,ctxD={t:null,r:null,c:null},hist=[],uiMode='v1';
const Q=s=>document.querySelector(s);

function toast(m,ok=true){const o=Q('.toast');if(o)o.remove();const d=document.createElement('div');d.className='toast '+(ok?'toast-ok':'toast-err');d.textContent=m;document.body.appendChild(d);setTimeout(()=>d.remove(),3000);}
function active(){if(actId===null&&T.length)actId=T[0].id;return T.find(t=>t.id===actId)||null;}
function setAct(id){actId=id;document.querySelectorAll('.card').forEach(c=>c.classList.toggle('active',+c.dataset.tid===actId));}
function getArea(){return uiMode==='v2'?Q('#tablesAreaV2'):Q('#tablesAreaV1');}
function upEmpty(){const a=getArea();const e=a.querySelector('.empty');if(!T.length&&!e)a.innerHTML='<div class="empty">Создайте таблицу — <b>Shift+1</b> RUB или <b>Shift+2</b> USD</div>';else if(T.length&&e)e.remove();}
function ci(cols,kw){return cols.findIndex(c=>c.toLowerCase().includes(kw.toLowerCase()));}
function cln(s){if(!s)return'';let x=String(s).trim().replace(/\s/g,'').replace(/,/g,'.').replace(/[^\d.\-]/g,'');const p=x.split('.');if(p.length>2)x=p[0]+'.'+p.slice(1).join('');if(x.includes('-')&&x.indexOf('-')>0)x=x.replace(/-/g,'');return x;}
function pn(v){const c=cln(v);return(c===''||c==='-'||c==='.')?NaN:parseFloat(c);}
function getQi(cols){return ci(cols,'Ко-во')>=0?ci(cols,'Ко-во'):ci(cols,'Количество');}
function calc(r,cols){const qi=getQi(cols),pi=ci(cols,'Цена'),ti=ci(cols,'Стоимость');if(qi>=0&&pi>=0&&ti>=0)r[ti]=((pn(r[qi])||0)*(pn(r[pi])||0)).toFixed(2);}
function sumT(td){const ti=ci(td.cols,'Стоимость');return ti<0?0:td.rows.reduce((s,r)=>s+(pn(r[ti])||0),0);}
function hdrs(cols,cur){return cols.map(c=>c.toLowerCase().startsWith('цена')?`Цена, ${cur} с НДС`:c.toLowerCase().startsWith('стоимость')?`Стоимость, ${cur} с НДС`:c);}
function ccl(n){const l=n.toLowerCase();if(l.includes('артикул'))return'col-article';if(l.includes('наименование'))return'col-name';if(l.includes('ко-во')||l.includes('количество'))return'col-qty';if(l.startsWith('цена'))return'col-price';if(l.startsWith('стоимость'))return'col-total';return'col-default';}
function cA(r,c){let s='';while(c>0){c--;s=String.fromCharCode(65+(c%26))+s;c=Math.floor(c/26);}return s+r;}

function addTable(cur='RUB'){upEmpty();idC++;const td={id:idC,cols:[...DC],rows:[['','','','','']],currency:cur,el:null,card:null};T.push(td);const a=getArea();const card=buildCardDOM(td);a.appendChild(card);td.card=card;setAct(td.id);render(td);toast(`Таблица ${cur} создана`);}
function dupTable(src){if(!src)src=active();if(!src)return;idC++;const td={id:idC,cols:[...src.cols],rows:src.rows.map(r=>[...r]),currency:src.currency,el:null,card:null};T.push(td);const a=getArea();const card=buildCardDOM(td);a.appendChild(card);td.card=card;render(td);toast('Дублирована');}

function buildCardDOM(td){const card=document.createElement('div');card.className='card';card.dataset.tid=td.id;card.addEventListener('click',e=>{if(!e.target.closest('button')&&!e.target.closest('input'))setAct(td.id);});card.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();const thEl=e.target.closest('thead th:not(.rn)');const trEl=e.target.closest('tbody tr');let ri=null,ci=null;if(thEl){const ths=[...card.querySelectorAll('thead th:not(.rn)')];ci=ths.indexOf(thEl);if(ci>=td.cols.length)ci=null;}if(trEl&&!trEl.classList.contains('tot')){ri=+trEl.dataset.ri;const tdEl=e.target.closest('td:not(.rn):not(.act-cell)');if(tdEl){const tds=[...trEl.querySelectorAll('td:not(.rn):not(.act-cell)')];ci=tds.indexOf(tdEl);if(ci>=td.cols.length)ci=null;}}ctxD={t:td.id,r:ri,c:ci};setAct(td.id);Q('#ctxMenu').style.display='block';Q('#ctxMenu').style.left=Math.min(e.clientX,window.innerWidth-220)+'px';Q('#ctxMenu').style.top=Math.min(e.clientY,window.innerHeight-400)+'px';});const hdr=document.createElement('div');hdr.className='card-hdr';hdr.innerHTML=`<span>📋 ${td.currency} с НДС <span class="badge badge-${td.currency==='USD'?'usd':'rub'}">${td.currency}</span><span class="badge badge-act">Активна</span></span><div class="card-acts"><button class="btn b-outline cur-btn" style="padding:4px 10px;font-size:11px;">${td.currency==='USD'?'💵 USD':'💰 RUB'}</button><button class="btn b-outline dup-btn" style="padding:4px 6px;font-size:11px;">📑</button><button class="btn b-red del-btn" style="padding:4px 10px;font-size:11px;">🗑</button></div>`;hdr.querySelector('.cur-btn').onclick=e=>{e.stopPropagation();td.currency=td.currency==='USD'?'RUB':'USD';hdr.querySelector('.cur-btn').textContent=td.currency==='USD'?'💵 USD':'💰 RUB';const badge=hdr.querySelector('.badge:not(.badge-act)');badge.textContent=td.currency;badge.className='badge badge-'+(td.currency==='USD'?'usd':'rub');hdr.querySelector('span').childNodes[0].textContent='📋 '+td.currency+' с НДС ';if(td.el)render(td);toast(`Валюта: ${td.currency}`);};hdr.querySelector('.dup-btn').onclick=e=>{e.stopPropagation();dupTable(td);};hdr.querySelector('.del-btn').onclick=e=>{e.stopPropagation();if(T.length<=1)return toast('Нужна хотя бы одна таблица!',0);card.remove();T.splice(T.indexOf(td),1);if(actId===td.id)actId=T.length?T[0].id:null;upEmpty();toast('Удалена');};const scr=document.createElement('div');scr.className='scroll';const tbl=document.createElement('table');tbl.innerHTML='<thead><tr></tr></thead><tbody></tbody>';scr.appendChild(tbl);card.appendChild(hdr);card.appendChild(scr);td.el=tbl;return card;}

function render(td){if(!td.el)return;const th=td.el.querySelector('thead tr'),tb=td.el.querySelector('tbody');th.innerHTML='<th class="rn">№</th>'+hdrs(td.cols,td.currency).map((h,i)=>`<th class="${ccl(td.cols[i])}">${h}</th>`).join('')+'<th style="width:44px"></th>';tb.innerHTML='';td.rows.forEach((r,ri)=>{const tr=document.createElement('tr');tr.dataset.ri=ri;const nt=document.createElement('td');nt.className='rn';nt.textContent=ri+1;tr.appendChild(nt);r.forEach((v,ci)=>{const tdEl=document.createElement('td');tdEl.className=ccl(td.cols[ci]);const inp=document.createElement('input');const cn=(td.cols[ci]||'').toLowerCase();if(cn.startsWith('стоимость')){inp.className='total';inp.readOnly=true;}inp.value=v??'';if(!cn.startsWith('стоимость'))inp.className=(cn.includes('ко-во')||cn.includes('количество'))?'qty':cn.startsWith('цена')?'price':'';if(cn.includes('наименование')){inp.style.whiteSpace='pre-wrap';inp.style.wordWrap='break-word';}inp.addEventListener('focus',()=>{tb.querySelectorAll('tr').forEach(r=>r.classList.remove('sel'));tr.classList.add('sel');});if((cn.includes('ко-во')||cn.includes('количество'))||cn.startsWith('цена')){inp.addEventListener('input',()=>{td.rows[ri][ci]=inp.value;updCalc(td);});inp.addEventListener('blur',()=>{const n=pn(td.rows[ri][ci]);if(!isNaN(n)){td.rows[ri][ci]=n.toFixed(2);inp.value=td.rows[ri][ci];updCalc(td);}});}else if(!cn.startsWith('стоимость')){inp.addEventListener('input',()=>{td.rows[ri][ci]=inp.value;});}inp.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.shiftKey){e.preventDefault();const s=inp.selectionStart,en=inp.selectionEnd,v=inp.value;inp.value=v.substring(0,s)+'\n'+v.substring(en);inp.selectionStart=inp.selectionEnd=s+1;td.rows[ri][ci]=inp.value;}else if(e.key==='Tab'&&!e.shiftKey){e.preventDefault();mvFocus(td,ri,ci,1);}else if(e.key==='Tab'&&e.shiftKey){e.preventDefault();mvFocus(td,ri,ci,-1);}else if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();mvFocus(td,ri,ci,0,1);}});tdEl.appendChild(inp);tr.appendChild(tdEl);});const at=document.createElement('td');at.className='act-cell';at.innerHTML='<div style="display:flex;gap:3px;justify-content:center;"><button class="rbtn rbtn-add">+</button><button class="rbtn rbtn-del">✕</button></div>';at.querySelector('.rbtn-add').onclick=e=>{e.stopPropagation();insRowBelow(td,ri);};at.querySelector('.rbtn-del').onclick=e=>{e.stopPropagation();delRow(td,ri);};tr.appendChild(at);tb.appendChild(tr);});const totTr=document.createElement('tr');totTr.className='tot';const ti=ci(td.cols,'Стоимость');totTr.innerHTML='<td class="rn"></td>'+td.cols.map((_,ci)=>{if(ci===(ti>=0?ti-1:td.cols.length-2))return'<td style="text-align:right;font-weight:700;padding-right:8px">Итого</td>';if(ci===ti)return`<td><input value="${sumT(td).toFixed(2)}" readonly class="total" style="font-weight:700"></td>`;return'<td></td>';}).join('')+'<td class="act-cell"></td>';tb.appendChild(totTr);}

function updCalc(td){if(!td||!td.el)return;const ti=ci(td.cols,'Стоимость');if(ti<0)return;const rows=td.el.querySelectorAll('tbody tr:not(.tot)');rows.forEach((tr,ri)=>{if(ri<td.rows.length){calc(td.rows[ri],td.cols);const tds=tr.querySelectorAll('td');if(tds[ti+1]){const inp=tds[ti+1].querySelector('input');if(inp&&document.activeElement!==inp)inp.value=td.rows[ri][ti]??'';}}});updTot(td);}
function mvFocus(td,ri,ci,dc,dr=0){let nr=ri+dr,nc=ci+dc;if(nc>=td.cols.length){nc=0;nr++;}if(nc<0){nc=td.cols.length-1;nr--;}if(nr>=td.rows.length)nr=0;if(nr<0)nr=td.rows.length-1;const rows=td.el.querySelectorAll('tbody tr:not(.tot)');if(nr>=0&&nr<rows.length){const tds=rows[nr].querySelectorAll('td:not(.rn):not(.act-cell)');if(nc>=0&&nc<tds.length){const inp=tds[nc].querySelector('input');if(inp){inp.focus();inp.select();}}}}
function updTot(td){if(!td.el)return;const tr=td.el.querySelector('tbody tr.tot');if(!tr)return;const ti=ci(td.cols,'Стоимость');if(ti<0)return;const tds=tr.querySelectorAll('td');if(tds[ti+1]){const inp=tds[ti+1].querySelector('input');if(inp)inp.value=sumT(td).toFixed(2);}}

function insRowBelow(td,idx){insRow(td,idx+1);}function insRowAbove(td,idx){insRow(td,idx);}
function insRow(td,idx){td.rows.splice(idx,0,Array(td.cols.length).fill(''));calc(td.rows[idx],td.cols);render(td);}
function delRow(td,idx){if(td.rows.length<=1)return toast('Нельзя удалить строку!',0);hist.push({a:'delRow',tid:td.id,d:{i:idx,r:[...td.rows[idx]]}});td.rows.splice(idx,1);render(td);}
function addRowEnd(td){td.rows.push(Array(td.cols.length).fill(''));calc(td.rows[td.rows.length-1],td.cols);render(td);}
function delRowEnd(td){if(td.rows.length<=1)return toast('Нельзя удалить строку!',0);td.rows.pop();render(td);}
function insCol(td,idx){const n=prompt('Название:','Новая колонка');if(!n||!n.trim())return;td.cols.splice(idx,0,n.trim());td.rows.forEach(r=>r.splice(idx,0,''));render(td);}
function delCol(td,idx){if(td.cols.length<=2)return toast('Минимум 2 колонки!',0);td.cols.splice(idx,1);td.rows.forEach(r=>r.splice(idx,1));render(td);}
function renameCol(td,idx){const old=td.cols[idx];const n=prompt('Новое название:',old);if(!n||!n.trim()||n.trim()===old)return;td.cols[idx]=n.trim();render(td);}
function addColEnd(td){const n=prompt('Название:','Новая колонка');if(!n||!n.trim())return;td.cols.push(n.trim());td.rows.forEach(r=>r.push(''));render(td);}
function delColEnd(td){if(td.cols.length<=2)return toast('Минимум 2 колонки!',0);td.cols.pop();td.rows.forEach(r=>r.pop());render(td);}

function parseCB(text){if(!text||!text.trim())return[];return text.trim().split(/\r?\n/).map(l=>l.includes('\t')?l.split('\t'):l.split('|')?l.split('|').map(c=>c.trim()).filter(c=>c):l.split(/\s{2,}/)).filter(r=>r.some(c=>c.trim()));}
function paste(){const td=active();if(!td)return toast('Выберите таблицу!',0);navigator.clipboard.readText().then(text=>{const p=parseCB(text);if(!p.length)return toast('Нет данных',0);p.forEach(r=>{const nr=[];for(let i=0;i<td.cols.length;i++){let v=r[i]??'';const cn=td.cols[i].toLowerCase();if(cn.includes('ко-во')||cn.includes('количество')||cn.startsWith('цена')){const n=pn(v);if(!isNaN(n))v=n.toFixed(2);}nr.push(v);}td.rows.push(nr);calc(nr,td.cols);});render(td);toast(`Вставлено строк: ${p.length}`);}).catch(()=>{const m=prompt('Вставьте:','');if(m){const p=parseCB(m);p.forEach(r=>{const nr=[];for(let i=0;i<td.cols.length;i++){let v=r[i]??'';const cn=td.cols[i].toLowerCase();if(cn.includes('ко-во')||cn.includes('количество')||cn.startsWith('цена')){const n=pn(v);if(!isNaN(n))v=n.toFixed(2);}nr.push(v);}td.rows.push(nr);calc(nr,td.cols);});render(td);}});}

function undo(){if(!hist.length)return toast('Нечего отменять',false);const l=hist.pop();const td=T.find(t=>t.id===l.tid);if(!td)return;td.rows.splice(l.d.i,0,l.d.r);render(td);toast('Отменено');}
function reRenderAll(){const a=getArea();a.innerHTML='';T.forEach(td=>{td.el=null;td.card=null;});T.forEach(td=>{const card=buildCardDOM(td);a.appendChild(card);td.card=card;});T.forEach(td=>{if(td.el)render(td);});upEmpty();}

// Инициализация
addTable('USD');